### PR TITLE
static to public

### PR DESCRIPTION
**Pull request by lm913**
Static variables within classes are not accessible after instantiation for example:

Within index.d.ts:
```javascript
/**
 * Options for saving a document in JPEG format.
 */
declare class JPEGSaveOptions {
	/**
	 * If true, the color profile is embedded in the document.
	 */
	static embedColorProfile: boolean;

	/**
	 * The download format to use.
	 */
	static formatOptions: FormatOptions;
        ...
```

When creating a new JPEGSaveOptions within a file:
```javascript
const saveOpts = new JPEGSaveOptions();
saveOpts.embedColorProfile = false; // [ts] Property 'embedColorProfile' does not exist on type 'JPEGSaveOptions'.
```

### CODE REVIEW

**Comment by pravdomil** [comment]
just delete static, do not add public keyword

**Comment by pravdomil** [comment]
Why you close it?

**Comment by SturmB** [comment]
I am also running into this issue. For example, `CMYKColor` (and all of the `Color` subclasses, for that matter) have their properties set as `static` when they should not be. I'll echo @martijnthe's question: Do you accept PRs?

**Comment by pravdomil** [comment]
I do accept PRs

**Pull request closed without merging**
