### PR TITLE
Overhauling ScriptUI

### PR DESCRIPTION
**Pull request by vespakoen**
I took `aftereffects.d.ts`'s ScriptUI types and merged all the current documentation into it.
I also took some missing documentation from here: http://estk.aenhancers.com/1%20-%20Introduction/index.html

I liked aftereffects.d.ts's ScriptUI types better, because it was more specific, mostly in the
`add('something')` methods, returning the correct type.

It also uses inheritance for the UI component removing a lot of duplication.

### CODE REVIEW

**Comment by pravdomil** [comment]
I think that's the way where to go, but for me is impossible to go thru all the changes.
Do you think that we can do it in smaller batches?
Start by modifying existing types to match the docs (you have mentioned) and aftereffects.d.ts?

**Comment by pravdomil** [comment]
`window.add` `group.add` `panel.add` fixed in https://github.com/pravdomil/types-for-adobe/commit/37806846bcc15ce7cd3513c2974bc7d809df01fd

**Comment by pravdomil** [comment]
inheritance https://github.com/pravdomil/types-for-adobe/commit/f783126a2f9a7496cf0307e7d376e18088fcc1ce

**Comment by vespakoen** [comment]
Ouch, I'm sorry man but I am nearing a deadline (for a tool that only has like 100loc ExtendScript)

I am helping out with the types because I released some bundlers & packagers and want them to work "out of the box" (https://github.com/adobe-extension-tools) but this is more of a pet project that is non-critical so to speak.

I am traveling the world with a friend on my Vespa (PK50) scooter so my time is very limited, my friends scooter broke down and we've been stuck in a hotel for 2 week (had a lot of time on my hands because of that) but now I should focus on other things to be honest.

I agree that doing it in smaller steps would probably be better, and it looks like you are already making some good progress!

Expect PR's from me but probably not anytime soon.

Good luck & see you later! ;)

**Comment by pravdomil** [comment]
I have pulled some common members up to `_Control` class and it drops from 4456 lines of code to 2658.

Let me know when you will be in Prague and thanks for support!

**Pull request closed without merging**
