### PR TITLE
ActionList and ActionReference types added

### PR DESCRIPTION
**Pull request by perludum**
completed ActionManager Code compatibility

### CODE REVIEW

**Comment by pravdomil** [comment]
send me please come code demonstrating usage of those classes

**Comment by perludum** [comment]
ActionManager Code is hardly human readable but can be recorded with the ScriptListener plugin while using Photoshop (see http://blogs.adobe.com/crawlspace/2006/05/installing_and_1.html)

The generated ActionManager code executes way faster in Photoshop than usual ExtendScript and can be useful when creating batch processes. This one creates a 800x600 document for example (using TS):

```
var idMk = app.charIDToTypeID("Mk  ");
var desc5 = new ActionDescriptor();
var idNw = app.charIDToTypeID("Nw  ");
var desc6 = new ActionDescriptor();
var idartboard = app.stringIDToTypeID("artboard");
desc6.putBoolean(idartboard, false);
var idMd = app.charIDToTypeID("Md  ");
var idRGBM = app.charIDToTypeID("RGBM");
desc6.putClass(idMd, idRGBM);
var idWdth = app.charIDToTypeID("Wdth");
var idRlt = app.charIDToTypeID("#Rlt");
desc6.putUnitDouble(idWdth, idRlt, 800.000000);
var idHght = app.charIDToTypeID("Hght");
var idRlt = app.charIDToTypeID("#Rlt");
desc6.putUnitDouble(idHght, idRlt, 600.000000);
var idRslt = app.charIDToTypeID("Rslt");
var idRsl = app.charIDToTypeID("#Rsl");
desc6.putUnitDouble(idRslt, idRsl, 72.000000);
var idpixelScaleFactor = app.stringIDToTypeID("pixelScaleFactor");
desc6.putDouble(idpixelScaleFactor, 1.000000);
var idFl = app.charIDToTypeID("Fl  ");
var idFl = app.charIDToTypeID("Fl  ");
var idTrns = app.charIDToTypeID("Trns");
desc6.putEnumerated(idFl, idFl, idTrns);
var idDpth = app.charIDToTypeID("Dpth");
desc6.putInteger(idDpth, 8);
var idprofile = app.stringIDToTypeID("profile");
desc6.putString(idprofile, "sRGB IEC61966-2.1");
var idGdes = app.charIDToTypeID("Gdes");
var list1 = new ActionList();
desc6.putList(idGdes, list1);
var idDcmn = app.charIDToTypeID("Dcmn");
desc5.putObject(idNw, idDcmn, desc6);
var idDocI = app.charIDToTypeID("DocI");
desc5.putInteger(idDocI, 196);
app.executeAction(idMk, desc5, DialogModes.NO);
```

**Comment by pravdomil** [comment]
and this is something like recording macros in psd?

**Comment by perludum** [comment]
yeah the listener is recording everything you do in PS! Can be useful sometimes.

**Pull request merged**
