### PR TITLE
Adding PremierePro CC2018 types

### PR DESCRIPTION
**Pull request by vespakoen**

### CODE REVIEW

**Comment by pravdomil** [comment]
where you have found the xml declaration file? in which directory?

**Comment by pravdomil** [comment]
there is some serious issues
```
index.d.ts(79,26): error TS1138: Parameter declaration expected.
index.d.ts(79,39): error TS1005: ';' expected.
index.d.ts(79,40): error TS1068: Unexpected token. A constructor, method, accessor, or property was expected.
index.d.ts(152,32): error TS1138: Parameter declaration expected.
index.d.ts(152,45): error TS1005: ';' expected.
index.d.ts(152,67): error TS1005: ';' expected.
index.d.ts(152,68): error TS1068: Unexpected token. A constructor, method, accessor, or property was expected.
index.d.ts(182,26): error TS1138: Parameter declaration expected.
index.d.ts(182,39): error TS1005: ';' expected.
index.d.ts(182,40): error TS1068: Unexpected token. A constructor, method, accessor, or property was expected.
index.d.ts(190,32): error TS1138: Parameter declaration expected.
index.d.ts(190,45): error TS1005: ';' expected.
index.d.ts(190,67): error TS1005: ';' expected.
index.d.ts(190,68): error TS1068: Unexpected token. A constructor, method, accessor, or property was expected.
index.d.ts(219,26): error TS1138: Parameter declaration expected.
index.d.ts(219,39): error TS1005: ';' expected.
index.d.ts(219,40): error TS1068: Unexpected token. A constructor, method, accessor, or property was expected.
index.d.ts(242,32): error TS1138: Parameter declaration expected.
index.d.ts(242,45): error TS1005: ';' expected.
index.d.ts(242,67): error TS1005: ';' expected.
index.d.ts(242,68): error TS1068: Unexpected token. A constructor, method, accessor, or property was expected.
index.d.ts(266,26): error TS1138: Parameter declaration expected.
index.d.ts(266,39): error TS1005: ';' expected.
index.d.ts(266,40): error TS1068: Unexpected token. A constructor, method, accessor, or property was expected.
index.d.ts(317,32): error TS1138: Parameter declaration expected.
index.d.ts(317,45): error TS1005: ';' expected.
index.d.ts(317,67): error TS1005: ';' expected.
index.d.ts(317,68): error TS1068: Unexpected token. A constructor, method, accessor, or property was expected.
index.d.ts(336,26): error TS1138: Parameter declaration expected.
index.d.ts(336,39): error TS1005: ';' expected.
index.d.ts(336,40): error TS1068: Unexpected token. A constructor, method, accessor, or property was expected.
index.d.ts(355,32): error TS1138: Parameter declaration expected.
index.d.ts(355,45): error TS1005: ';' expected.
index.d.ts(355,67): error TS1005: ';' expected.
index.d.ts(355,68): error TS1068: Unexpected token. A constructor, method, accessor, or property was expected.
index.d.ts(380,26): error TS1138: Parameter declaration expected.
index.d.ts(380,39): error TS1005: ';' expected.
index.d.ts(380,40): error TS1068: Unexpected token. A constructor, method, accessor, or property was expected.
index.d.ts(410,32): error TS1138: Parameter declaration expected.
index.d.ts(410,45): error TS1005: ';' expected.
index.d.ts(410,67): error TS1005: ';' expected.
index.d.ts(410,68): error TS1068: Unexpected token. A constructor, method, accessor, or property was expected.
index.d.ts(439,26): error TS1138: Parameter declaration expected.
index.d.ts(439,39): error TS1005: ';' expected.
index.d.ts(439,40): error TS1068: Unexpected token. A constructor, method, accessor, or property was expected.
index.d.ts(447,32): error TS1138: Parameter declaration expected.
index.d.ts(447,45): error TS1005: ';' expected.
index.d.ts(447,67): error TS1005: ';' expected.
index.d.ts(447,68): error TS1068: Unexpected token. A constructor, method, accessor, or property was expected.
index.d.ts(486,26): error TS1138: Parameter declaration expected.
index.d.ts(486,39): error TS1005: ';' expected.
index.d.ts(486,40): error TS1068: Unexpected token. A constructor, method, accessor, or property was expected.
index.d.ts(494,32): error TS1138: Parameter declaration expected.
index.d.ts(494,45): error TS1005: ';' expected.
index.d.ts(494,67): error TS1005: ';' expected.
index.d.ts(494,68): error TS1068: Unexpected token. A constructor, method, accessor, or property was expected.
index.d.ts(551,26): error TS1138: Parameter declaration expected.
index.d.ts(551,39): error TS1005: ';' expected.
index.d.ts(551,40): error TS1068: Unexpected token. A constructor, method, accessor, or property was expected.
index.d.ts(693,32): error TS1138: Parameter declaration expected.
index.d.ts(693,45): error TS1005: ';' expected.
index.d.ts(693,67): error TS1005: ';' expected.
index.d.ts(693,68): error TS1068: Unexpected token. A constructor, method, accessor, or property was expected.
index.d.ts(732,26): error TS1138: Parameter declaration expected.
index.d.ts(732,39): error TS1005: ';' expected.
index.d.ts(732,40): error TS1068: Unexpected token. A constructor, method, accessor, or property was expected.
index.d.ts(765,32): error TS1138: Parameter declaration expected.
index.d.ts(765,45): error TS1005: ';' expected.
index.d.ts(765,67): error TS1005: ';' expected.
index.d.ts(765,68): error TS1068: Unexpected token. A constructor, method, accessor, or property was expected.
index.d.ts(834,26): error TS1138: Parameter declaration expected.
index.d.ts(834,39): error TS1005: ';' expected.
index.d.ts(834,40): error TS1068: Unexpected token. A constructor, method, accessor, or property was expected.
index.d.ts(859,32): error TS1138: Parameter declaration expected.
index.d.ts(859,45): error TS1005: ';' expected.
index.d.ts(859,67): error TS1005: ';' expected.
index.d.ts(859,68): error TS1068: Unexpected token. A constructor, method, accessor, or property was expected.
index.d.ts(915,26): error TS1138: Parameter declaration expected.
index.d.ts(915,39): error TS1005: ';' expected.
index.d.ts(915,40): error TS1068: Unexpected token. A constructor, method, accessor, or property was expected.
index.d.ts(1061,32): error TS1138: Parameter declaration expected.
index.d.ts(1061,45): error TS1005: ';' expected.
index.d.ts(1061,67): error TS1005: ';' expected.
index.d.ts(1061,68): error TS1068: Unexpected token. A constructor, method, accessor, or property was expected.
index.d.ts(1096,26): error TS1138: Parameter declaration expected.
index.d.ts(1096,39): error TS1005: ';' expected.
index.d.ts(1096,40): error TS1068: Unexpected token. A constructor, method, accessor, or property was expected.
index.d.ts(1104,32): error TS1138: Parameter declaration expected.
index.d.ts(1104,45): error TS1005: ';' expected.
index.d.ts(1104,67): error TS1005: ';' expected.
index.d.ts(1104,68): error TS1068: Unexpected token. A constructor, method, accessor, or property was expected.
index.d.ts(1128,26): error TS1138: Parameter declaration expected.
index.d.ts(1128,39): error TS1005: ';' expected.
index.d.ts(1128,40): error TS1068: Unexpected token. A constructor, method, accessor, or property was expected.
index.d.ts(1136,32): error TS1138: Parameter declaration expected.
index.d.ts(1136,45): error TS1005: ';' expected.
index.d.ts(1136,67): error TS1005: ';' expected.
index.d.ts(1136,68): error TS1068: Unexpected token. A constructor, method, accessor, or property was expected.
index.d.ts(1160,26): error TS1138: Parameter declaration expected.
index.d.ts(1160,39): error TS1005: ';' expected.
index.d.ts(1160,40): error TS1068: Unexpected token. A constructor, method, accessor, or property was expected.
index.d.ts(1168,32): error TS1138: Parameter declaration expected.
index.d.ts(1168,45): error TS1005: ';' expected.
index.d.ts(1168,67): error TS1005: ';' expected.
index.d.ts(1168,68): error TS1068: Unexpected token. A constructor, method, accessor, or property was expected.
index.d.ts(1192,26): error TS1138: Parameter declaration expected.
index.d.ts(1192,39): error TS1005: ';' expected.
index.d.ts(1192,40): error TS1068: Unexpected token. A constructor, method, accessor, or property was expected.
index.d.ts(1200,32): error TS1138: Parameter declaration expected.
index.d.ts(1200,45): error TS1005: ';' expected.
index.d.ts(1200,67): error TS1005: ';' expected.
index.d.ts(1200,68): error TS1068: Unexpected token. A constructor, method, accessor, or property was expected.
index.d.ts(1254,26): error TS1138: Parameter declaration expected.
index.d.ts(1254,39): error TS1005: ';' expected.
index.d.ts(1254,40): error TS1068: Unexpected token. A constructor, method, accessor, or property was expected.
index.d.ts(1262,32): error TS1138: Parameter declaration expected.
index.d.ts(1262,45): error TS1005: ';' expected.
index.d.ts(1262,67): error TS1005: ';' expected.
index.d.ts(1262,68): error TS1068: Unexpected token. A constructor, method, accessor, or property was expected.
index.d.ts(1286,26): error TS1138: Parameter declaration expected.
index.d.ts(1286,39): error TS1005: ';' expected.
index.d.ts(1286,40): error TS1068: Unexpected token. A constructor, method, accessor, or property was expected.
index.d.ts(1294,32): error TS1138: Parameter declaration expected.
index.d.ts(1294,45): error TS1005: ';' expected.
index.d.ts(1294,67): error TS1005: ';' expected.
index.d.ts(1294,68): error TS1068: Unexpected token. A constructor, method, accessor, or property was expected.
index.d.ts(1318,26): error TS1138: Parameter declaration expected.
index.d.ts(1318,39): error TS1005: ';' expected.
index.d.ts(1318,40): error TS1068: Unexpected token. A constructor, method, accessor, or property was expected.
index.d.ts(1326,32): error TS1138: Parameter declaration expected.
index.d.ts(1326,45): error TS1005: ';' expected.
index.d.ts(1326,67): error TS1005: ';' expected.
index.d.ts(1326,68): error TS1068: Unexpected token. A constructor, method, accessor, or property was expected.
index.d.ts(1360,26): error TS1138: Parameter declaration expected.
index.d.ts(1360,39): error TS1005: ';' expected.
index.d.ts(1360,40): error TS1068: Unexpected token. A constructor, method, accessor, or property was expected.
index.d.ts(1368,32): error TS1138: Parameter declaration expected.
index.d.ts(1368,45): error TS1005: ';' expected.
index.d.ts(1368,67): error TS1005: ';' expected.
index.d.ts(1368,68): error TS1068: Unexpected token. A constructor, method, accessor, or property was expected.
index.d.ts(1402,26): error TS1138: Parameter declaration expected.
index.d.ts(1402,39): error TS1005: ';' expected.
index.d.ts(1402,40): error TS1068: Unexpected token. A constructor, method, accessor, or property was expected.
index.d.ts(1458,32): error TS1138: Parameter declaration expected.
index.d.ts(1458,45): error TS1005: ';' expected.
index.d.ts(1458,67): error TS1005: ';' expected.
index.d.ts(1458,68): error TS1068: Unexpected token. A constructor, method, accessor, or property was expected.
index.d.ts(1482,26): error TS1138: Parameter declaration expected.
index.d.ts(1482,39): error TS1005: ';' expected.
index.d.ts(1482,40): error TS1068: Unexpected token. A constructor, method, accessor, or property was expected.
index.d.ts(1520,32): error TS1138: Parameter declaration expected.
index.d.ts(1520,45): error TS1005: ';' expected.
index.d.ts(1520,67): error TS1005: ';' expected.
index.d.ts(1520,68): error TS1068: Unexpected token. A constructor, method, accessor, or property was expected.
index.d.ts(1614,26): error TS1138: Parameter declaration expected.
index.d.ts(1614,39): error TS1005: ';' expected.
index.d.ts(1614,40): error TS1068: Unexpected token. A constructor, method, accessor, or property was expected.
index.d.ts(1686,32): error TS1138: Parameter declaration expected.
index.d.ts(1686,45): error TS1005: ';' expected.
index.d.ts(1686,67): error TS1005: ';' expected.
index.d.ts(1686,68): error TS1068: Unexpected token. A constructor, method, accessor, or property was expected.
index.d.ts(1722,26): error TS1138: Parameter declaration expected.
index.d.ts(1722,39): error TS1005: ';' expected.
index.d.ts(1722,40): error TS1068: Unexpected token. A constructor, method, accessor, or property was expected.
index.d.ts(1764,32): error TS1138: Parameter declaration expected.
index.d.ts(1764,45): error TS1005: ';' expected.
index.d.ts(1764,67): error TS1005: ';' expected.
index.d.ts(1764,68): error TS1068: Unexpected token. A constructor, method, accessor, or property was expected.
index.d.ts(1813,26): error TS1138: Parameter declaration expected.
index.d.ts(1813,39): error TS1005: ';' expected.
index.d.ts(1813,40): error TS1068: Unexpected token. A constructor, method, accessor, or property was expected.
index.d.ts(1831,32): error TS1138: Parameter declaration expected.
index.d.ts(1831,45): error TS1005: ';' expected.
index.d.ts(1831,67): error TS1005: ';' expected.
index.d.ts(1831,68): error TS1068: Unexpected token. A constructor, method, accessor, or property was expected.
index.d.ts(1872,26): error TS1138: Parameter declaration expected.
index.d.ts(1872,39): error TS1005: ';' expected.
index.d.ts(1872,40): error TS1068: Unexpected token. A constructor, method, accessor, or property was expected.
index.d.ts(1891,32): error TS1138: Parameter declaration expected.
index.d.ts(1891,45): error TS1005: ';' expected.
index.d.ts(1891,67): error TS1005: ';' expected.
index.d.ts(1891,68): error TS1068: Unexpected token. A constructor, method, accessor, or property was expected.
```

**Comment by vespakoen** [comment]
[omv$premierepro-12.0$12.0.xml.zip](https://github.com/pravdomil/types-for-adobe/files/1544708/omv.premierepro-12.0.12.0.xml.zip)

Here you go

**Comment by pravdomil** [comment]
thanks for xml file

issue fixed in https://github.com/pravdomil/extendscript-xml-to-typescript/commit/492ba46845066980578a62d138339e31208c6d50
premiere types added in https://github.com/pravdomil/types-for-adobe/commit/ff5198475bc30a607dbe92e7767e6ec8cb8e6c9c

**Pull request closed without merging**
