### PR TITLE
fix #57

### LINKED ISSUE #57: AE：Redo CommandID is  wrong.
The correct value is 2035.

https://github.com/pravdomil/Types-for-Adobe/blob/a7a1ea8db7bf6848ee4b8abcb57004eba62c9863/AfterEffects/2018/index.d.ts#L106

### PR DESCRIPTION
**Pull request by fz-qs**

### CODE REVIEW

**Comment by pravdomil** [comment]
can we add it as Redo2?

**Comment by fz-qs** [comment]
Why? I have verified that Redo's ID is 2035 in all After Effects since 2018.

**Comment by pravdomil** [comment]
redo=17 is in official docs, can we can set redo=2035 and redo2=17?

**Comment by fz-qs** [comment]
ok.

**Pull request closed without merging**
